### DISCUSSION TITLE
[How to] What do you do if Allure TestOps does not start after 2021-07 update and has RabbitMQ related strings in logs

### DISCUSSION THREAD

**Discussion by cheshi-mantu** [allure-framework/allure2#1371] [TestOps]
Hello there!
Guys, if you updated Allure TestOps in the end of July / beginning of August 2021 and it suddenly does not start do the following:

1. check if RabbitMQ container is running. If not, check the logs to contain the following
```bash
error: RABBITMQ_DEFAULT_PASS is set but deprecated
error: RABBITMQ_DEFAULT_USER is set but deprecated
error: RABBITMQ_DEFAULT_VHOST is set but deprecated
error: deprecated environment variables detected
```
2. Check if logs of report service contain something like that: 

 ```bash
org.springframework.amqp.AmqpConnectException: org.springframework.amqp.AmqpAuthenticationException: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
```
3. If the logs do contain these strings, then you need to update your **docker-compose.yaml** config as follows:

## As is

    image: rabbitmq:management

## to be

    image: rabbitmq:3.8-management

Having this setting updated will temporary remove the problem until we've found proper fix.

**Comment by init-penguin** [comment]
Well, here is workaround we've been using since RMQ:latest upgrade:
```
...
report-mq:
    image: rabbitmq:management
    volumes:
      - report-mq-volume:/var/lib/rabbitmq
      - ./allure/rmq-config:/etc/rabbitmq
    networks:
      - allure
...
```
Contents of `./allure/rmq-config/rabbitmq.conf`
```
loopback_users.report=false
default_vhost=report
default_user=report
default_pass=P@assw0rd
```
