### DISCUSSION TITLE
Deploying allure report to github actions only deploys the last test that ran in github actions.

### DISCUSSION THREAD

**Discussion by Romarionijim** [allure-framework/allure2#2260] [Questions & Support] [answered]
hello, i'm using allure report along with pytest and playwright for test automation, I am using an action that deploys the allure report to github pages, the problem is that the deployment of the allure report only happens for the last test that has been run and does not deploy the other tests, 
i'm running my tests by using pytest mark fixture, each mark is put into a an array of matrix in github actions script, 
my question, how can I deploy each report to gh-pages?  tried multiple approaches but none of them seems to work.

my ci.yml file

```yml
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        marks: [ 'LOGIN','PRODUCT' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install playwright browsers
        run: python -m playwright install --with-deps
      - name: Run tests
        run: pytest -m ${{ matrix.marks }} --tracing=retain-on-failure
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results-${{ matrix.marks }}
          path: allure-results-${{ matrix.marks }}
      - name: configure allure using allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
```

my repo:

https://github.com/Romarionijim/github-pages-allure-test

I would appreciate for some guidance or help because I was not able to find a solution on this matter, thanks!
