### DISCUSSION TITLE
Allure Report extension for Azure DevOps

### DISCUSSION THREAD

**Discussion by ciconq** [allure-framework/allure2#2337] [Questions & Support] [answered]
Hello, 

I am currently testing out Allure Report [extension](https://marketplace.visualstudio.com/items?itemName=qameta.allure-azure-pipelines) for Azure DevOps. I have built a simple .NET 7 based NUnit framework wih a couple of tests which are passing both locally and on the pipeline and I am able to successfully generate and view a report locally via the CLI.

I am having the following configuration for running the tests and publishing the Allure report in the `.yml` file:
``` 
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
      
  - task: PublishAllureReport@1
    displayName: 'Publish Allure report'
    inputs:
      allureVersion: "2.26.0"
      testResultsDir: "$(System.DefaultWorkingDirectory)/$(projectName)/bin/$(buildConfiguration)/net7.0"
```

Also this is the `allureConfig.json` that I am using: 
```
{
  "allure": {
    "directory": "allure-results"
  }
}
```

I can see in the `Publish Allure report` task that the `allure-results` folder is successfully created within the specified directory in `testResultsDir` as no message in logs is thrown that `allure-results` folder does not exist(as well as debugging via script to check that `allure-results` is created in `testResultsDir`) but what I am seeing after the `Publish Allure report` task is completed(logs within it) is:

```
Report successfully generated to "$(System.DefaultWorkingDirectory)/RandomUUID"
```

Not sure if the issue is because of the RandomUUID(assuming `allure-report` folder) is created within the project root and `allure-results` is in different folder. I have tried adding several scripts that create `allure-results` folder within the project root and copying all the contents of the one that is in a different directory to the newly created `allure-results` folder as well as checking for UUID directories within project root and renaming them to `allure-report` from which I can see that there is an `index.html` file(nothing else like `data` folder and related directories and files when report is generated locally) but still getting the following when trying to open the report once the pipeline has finished:

![allure-report-issue](https://github.com/allure-framework/allure2/assets/16039275/4abede78-33f3-4786-b097-f16dd244820a)

Would appreciate any suggestions or ideas, thank you for your time and attention!
