### DISCUSSION TITLE
How to display different reports for each stage (environment) using the azure devops extension

### DISCUSSION THREAD

**Discussion by kholoudmohamed** [allure-framework/allure2#2370] [Questions & Support]
I'm using the new official azure devops extension to view Allure report on the pipeline
And I'm using allure with Nunit

This is how My pipeline is setup
![image](https://github.com/allure-framework/allure2/assets/4224381/7f5dca0d-44b3-4ed9-bff0-9f00656bcee6)

And this is how I use the extension in yaml file
![image](https://github.com/allure-framework/allure2/assets/4224381/5f03b91b-bf43-411c-bf1a-0e401762bec7)

And it works, I can see the report but the problem is that it's displaying the one finished the latest
Instead I was expecting two reports one for test and one for staging
Is this possible to achieve?

**Comment by epszaw** [comment]
Hey there! Sounds like a new feature. Will research, how it's possible to reach the expected result and write you back 🙏

**Comment by epszaw** [comment]
Hey there! Since version `1.2.0` you can render several reports at once.

Just add as many tasks as you want with different `testResultsDir ` and `reportName` inputs. For example:

```yaml
- task: PublishAllureReport@1
  displayName: "publish allure report"
  inputs:
    testResultsDir: "path/to/allure-results"
    reportName: "Report 1"

- task: PublishAllureReport@1
  displayName: "publish allure report"
  inputs:
    testResultsDir: "path/to/another-allure-results"
    reportName: "Report 2"
```

<img width="1108" alt="image" src="https://github.com/allure-framework/allure2/assets/13414205/202bad0a-908a-4c92-8398-a9a6bba71051">
