### DISCUSSION TITLE
Help with integrating the Allure report with Azure DevOps

### DISCUSSION THREAD

**Discussion by RodrigoOBC** [allure-framework/allure2#2379] [Questions & Support] [answered]
Good morning,

I'm trying to integrate the report generated from tests with Azure DevOps, but I'm having trouble.

The documents generated for the report are created in the "./temp" folder. However, it can't find the folder with the Index.html file. It tries to search for the file inside the "temp" folder.

Currently, I'm using:

```
- task: PublishAllureReport@1
  displayName: Publish Report
  inputs:
    allureVersion: 2.27.0
    reportDir: allure-results
    testResultsDir: temp

```

However, I'm encountering the following error:

However, I'm encountering the following error:

```
##[warning]ENOENT: no such file or directory, open '/__w/1/s/temp/index.html'

```

When I change the folder order, it presents this error:

```
##[error]Unhandled: Not found reportDir: /__w/1/s/allure-results
##[error]Error: Not found reportDir: /__w/1/s/allure-results

```

**Comment by RodrigoOBC** [comment]
Update: 

I realized I was using the unofficial Allure Report library for Azure DevOps. Now I'm using the correct command:

`- task: PublishAllureReport@1
  displayName: Publish Report
  inputs:
    allureVersion: 2.25.0
    testResultsDir: \"$(Build.SourcesDirectory)/temp\"
`

Now I'm using the correct library, however, I'm receiving the following error:


`ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.`

**Comment by RodrigoOBC** [comment, marked as answer]
Good morning,

I managed to solve the problem using the following code in the Pipeline:

```

- stage: PublishReport
  displayName: 'Publish report'
  jobs:     
  - job: PublishReport
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/openjdk/jdk:17-ubuntu
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'pasta-gerada'
          path: "$(Build.SourcesDirectory)/temp"
      - task: PublishAllureReport@1
        displayName: Publish Report
        inputs:
          allureVersion: 2.25.0
          testResultsDir: temp

```

Basically, I created a Java container, imported the 'temp' folder from another execution, and generated the report within it.
