### DISCUSSION TITLE
Allure extension for Azure DevOps overwrites test results for each rerun failed tests execution

### DISCUSSION THREAD

**Discussion by ciconq** [allure-framework/allure2#2387] [Questions & Support] [answered]
Hello, 

I am trying to find a way, if it is possible, to have a single(merged) Allure report for all tests including ones ran if failed.

I am using `VSTest@3` task which is the following:

```
      - task: VSTest@3
        displayName: 'Test run'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*Tests*.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          runTestsInIsolation: false
          codeCoverageEnabled: true
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          rerunFailedTests: true
          rerunType: 'basedOnTestFailureCount'
          rerunFailedTestCasesMaxLimit: '50'
          rerunMaxAttempts: '2'
```

Every failed test is ran in the current task(`VSTest@3`) and for example if I have 4 tests and 3 pass on the 1st run then the 1 that failed passes as well on the 1st rerun, I am getting an overwritten Allure report which has only 1 test(last one) and not all 4 of them.

This is my `PublishAllureReport@1` task:

```
      - task: PublishAllureReport@1
        displayName: 'Publish allure report'
        inputs:
          allureVersion: '2.26.0'
          testResultsDir: '$(allureResultsPath)'
```

Would appreciate any feedback or suggestions but as I said I am not sure if this is supported. 

Thank you for your time and attention!
