### DISCUSSION TITLE
When I run the pipeline in Azure DevOps, the following error is presented: Something went wrong while fetching the report! Failed to fetch

### DISCUSSION THREAD

**Discussion by RodrigoOBC** [allure-framework/allure2#2406] [Questions & Support]
I have a pipeline that runs daily in Azure DevOps, where I perform tests with Playwright, and after the tests, I publish the data using the following tool 'Allure Report by Qameta Software,' as indicated in the Allure documentation itself. However, on some days, it runs perfectly, and on others, it presents the error shown in the photo below

![image](https://github.com/allure-framework/allure2/assets/32024711/801b2532-ddae-4b3c-9988-86b2e7eff9ef)

The code I use to perform the publication is as follows:

```yaml
- task: PublishAllureReport@1
  displayName: Publish Report
  inputs:
    allureVersion: 2.27.0
    testResultsDir: temp
```
