### DISCUSSION TITLE
Supporting multiple publish allure report tasks in the same pipeline.  Currently the second publish will overwrite the first one

### DISCUSSION THREAD

**Discussion by anthony0lai** [allure-framework/allure2#2488] [Documentation]
Our Azure devops CI/CD pipeline is running multiple test stages with each publishing allure results (using cypress).  As a result,  `PublishAllureReport@1` are called multiple times.  In this example, there are 3 tests running in the first publish, and 24 tests in the second publish
![image](https://github.com/allure-framework/allure2/assets/37915758/1b6d8761-5c76-4c04-b303-9162af44c058)

While expecting in this case, either
* There are two allure reports showing up in pipeline result, or
* Single allure report is shown, but contains results from the both test

However, the allure report is showing only test results from the second test run.  Is there anyway to merge multiple `allure-results` when generating reports?
![image](https://github.com/allure-framework/allure2/assets/37915758/93d87402-8aac-4411-9987-f177c866f2be)

**Comment by epszaw** [comment]
Hey there!

1. Both tasks in your configurations look for test results in the same directory (by default, `testResultsDir` input has `./allure-results` value). If the context directory is the same one – you will have two same reports. Rename your `reportDir` parameter to `testResultsDir` because there is no `reportDir` supported input option.
2. Try to add `reportName` input to make tabs different. I'm not sure, that it could solve the problem, but let's give a try: 

```yaml
  - task: PublishAllureReportDev@1
    displayName: "publish allure report 1"
    inputs:
      reportName: "Report 1"
      

  - task: PublishAllureReportDev@1
    displayName: "publish allure report 2"
    inputs:
      reportName: "Report 2"
```
