### DISCUSSION TITLE
Allure Report in Azure DevOps Pipelines for Playwright .net tests has an error: JAVA_HOME is not set and no 'java'

### DISCUSSION THREAD

**Discussion by TomJarFab** [allure-framework/allure2#2568] [Questions & Support] [answered]
I try to run a that yml in Azure DevOps Pipelines:
```
trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright/dotnet:v1.44.0-jammy

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'
  displayName: 'Use .NET SDK'

- script: dotnet build --configuration Release
  displayName: 'Build'
- script: dotnet test --configuration Release --logger "nunit;LogFilePath=$(System.DefaultWorkingDirectory)/TestResults/TEST-Results.xml"
  displayName: 'Run tests'
  continueOnError: true 

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/TestResults/'
  displayName: 'Publish Test Results'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'ls $(System.DefaultWorkingDirectory)/TestResults/'
    
- task: PublishAllureReport@1
  displayName: "publish allure report"
  inputs:
    testResultsDir: '$(System.DefaultWorkingDirectory)/TestResults/'
    allureVersion: "2.29.0"
```
    
All go smooth to the point publish allure report. I got an error:

> Starting: publish allure report
> ==============================================================================
> Task         : Publish Allure Report
> Description  : Task for generate and publish Allure Report
> Version      : 1.4.0
> Author       : Qameta Software Inc.
> Help         : Generate and publish Allure Report
> ==============================================================================
> Found 1 test results files.
> Downloading Allure CLI from https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
> Downloading: https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
> Caching tool: allure 2.29.0 x64
> Prepending PATH environment variable with directory: /__w/1/s/c549fad9-cd87-4ef6-86ec-197065f1faa4/allure-2.29.0/bin
> /__w/1/s/c549fad9-cd87-4ef6-86ec-197065f1faa4/allure-2.29.0/bin/allure generate --single-file --name Allure Report --clean -o /__w/1/s/446571b8-3632-4800-a87c-ebb89cfab81b /__w/1/s/TestResults/
> 
> ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
> 
> Please set the JAVA_HOME variable in your environment to match the
> location of your Java installation.
> 
> undefined
> ##[error]Unknown error, see pipeline log for more details
> Finishing: publish allure report

What am I doing wrong? It seems pretty easy on this web: https://allurereport.org/docs/integrations-azure/

**Comment by baev** [comment, marked as answer]
The issue is that you're running it on `playwright/dotnet` container, which doesn't have Java installed. Default Azure agents have Java pre-installed, but since you're running tasks in the playwright container, you must add steps to install JRE.

**Comment by TomJarFab** [comment]
Thank you @baev for answer.
For future reference for other people:
```
trigger:
- master

pool:
  vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright/dotnet:v1.44.1-jammy

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install JDK8'

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'
  displayName: 'Use .NET SDK'

- script: dotnet build --configuration Release
  displayName: 'Build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pwsh $(System.DefaultWorkingDirectory)/uitests/bin/Release/net8.0/playwright.ps1 install'
  displayName: 'Update playwright'   

- script: dotnet test --configuration Release --logger "nunit;LogFilePath=$(System.DefaultWorkingDirectory)/TestResults/TEST-Results.xml"
  displayName: 'Run tests'
  continueOnError: true 

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/TestResults/'
  displayName: 'Publish Test Results'
  
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/uitests/bin/Release/net8.0/Trace/'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
  displayName: 'Publish Trace'

- task: PublishAllureReport@1
  displayName: "Publish Allure Report"
  inputs:
    testResultsDir: '$(System.DefaultWorkingDirectory)/uitests/bin/Release/net8.0/allure-results'
    allureVersion: "2.29.0"

```
