### DISCUSSION TITLE
Allure Report in Azure DevOps Pipelines doesn't show Trend graph

### DISCUSSION THREAD

**Discussion by TomJarFab** [allure-framework/allure2#2573] [Questions & Support] [answered]
I have running Allure Report using this Yml and I have missing Trend graph. How I can fix that?
```
pool:
  vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright/dotnet:v1.44.1-jammy

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install JDK8'

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.0.x'
    displayName: 'Use .NET SDK'

  - script: dotnet build --configuration Release
    displayName: 'Build'

  - script: dotnet test --configuration Release --logger "nunit;LogFilePath=$(System.DefaultWorkingDirectory)/TestResults/TEST-Results.xml"
    displayName: 'Run tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/TestResults/'
    displayName: 'Publish Test Results'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/uitests/bin/Release/net8.0/Trace/'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'
    condition: succeededOrFailed()
    displayName: 'Publish Trace'

  - task: PublishAllureReport@1
    displayName: "Publish Allure Report"
    inputs:
      testResultsDir: '$(System.DefaultWorkingDirectory)/uitests/bin/Release/net8.0/allure-results'
      allureVersion: "2.29.0"
```

![image](https://github.com/allure-framework/allure2/assets/125563776/4e295d27-f6fa-48eb-90ed-17699a57c920)

What am I missing? How I can make it work? It seems for me that Allure doesn't have an access to historical data.

**Comment by TomJarFab** [comment]
@baev  Can you help with it? Any idea what could be wrong?

**Reply by baev** [reply, marked as answer]
History isn't supported for Azure at the moment

**Reply by TomJarFab** [reply]
Is there any timeline for when it will be available?

**Reply by baev** [reply]
It's in backlog, but no ETA yet available. I'll discuss it with the dev team next week

**Reply by TomJarFab** [reply]
@baev Is there any update? Is there a way to track progress on this item/task by myself?

**Reply by IlliaAbielientsev** [reply]
@TomJarFab as workaround u can use artifacts from previous succeeded build(need extra report generation) and add history to allure files

**Reply by SaiSDET** [reply]
@IlliaAbielientsev to do that we need to install npm and use allure generate to create the raw report data? Once i have that history data i could upload to S3. Would that work?

**Reply by LelikTov** [reply]
@baev  could you let us know when the issue is fixed?

It is quite hard to distinguish whether it is a new failed test or an old one.

**Comment by ymouhat** [comment]
Hi @baev 
I hope you are doing well. 
Is possible to have visibility if this feature will be supported in standard and if when it could be delivered ? 
Thank you in advance.

**Comment by Jaryn91** [comment]
It's a simplified version of what works for me:
```
pool:
  name: pool_for_tests

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: run_tests
        displayName: RunTests
        container: mcr.microsoft.com/playwright/dotnet:v1.50.0-noble
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: "8.x"
            displayName: "Use .NET SDK"

          - script: dotnet build --configuration Release
            displayName: "Build"

          - script: dotnet test --configuration Release --logger "nunit;LogFilePath=$(System.DefaultWorkingDirectory)/TestResults/TEST-Results.xml"
            displayName: "Run tests"
            continueOnError: true

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "NUnit"
              testResultsFiles: "**/*.xml"
              searchFolder: "$(System.DefaultWorkingDirectory)/TestResults/"
            displayName: "Publish Test Results"

          - task: PublishPipelineArtifact@1
            displayName: "Publish Allure Results"
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/TestProject/bin/Release/net8.0/allure-results"
              artifact: "allure-results"
              publishLocation: "pipeline"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/TestProject/bin/Release/net8.0/Trace/"
              artifact: "playwright-report"
              publishLocation: "pipeline"
            condition: and(succeededOrFailed(), eq(variables['CheckTraceFolder.traceFolderExists'], 'true'))
            displayName: "Publish Trace"

  - stage: Allure
    displayName: Allure
    dependsOn: Build
    jobs:
      - job: Allure
        displayName: Publish Allure
        container: eclipse-temurin:17-jdk
        steps:
          - task: DownloadPipelineArtifact@1
            displayName: "Download Test Results"
            inputs:
              artifact: "allure-results"
              downloadPath: "$(System.DefaultWorkingDirectory)/"

          - task: DownloadPipelineArtifact@2
            displayName: "Download Previous Allure History"
            inputs:
              buildType: "specific"
              project: "$(System.TeamProjectId)"
              definition: "$(System.DefinitionId)"
              buildVersionToDownload: "latestFromBranch"
              branchName: "$(Build.SourceBranch)"
              allowPartiallySucceededBuilds: true
              allowFailedBuilds: true
              artifact: "allure-history"
              path: "$(System.DefaultWorkingDirectory)/allure-history"
            continueOnError: true

          - task: Bash@3
            displayName: "Generate Allure Report with History"
            inputs:
              targetType: "inline"
              script: |
                # Copy previous history to allure-results if exists
                if [ -d "$(System.DefaultWorkingDirectory)/allure-history/history" ]; then
                  cp -r "$(System.DefaultWorkingDirectory)/allure-history/history" "$(System.DefaultWorkingDirectory)/allure-results/"
                fi
                
                # Download and run Allure CLI
                ALLURE_VERSION="2.34.1"
                curl -sL "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz" | tar -xz -C /tmp
                /tmp/allure-${ALLURE_VERSION}/bin/allure generate --clean -o "$(System.DefaultWorkingDirectory)/allure-report" "$(System.DefaultWorkingDirectory)/allure-results"
                
                # Prepare history for next build
                mkdir -p "$(System.DefaultWorkingDirectory)/allure-history-output"
                cp -r "$(System.DefaultWorkingDirectory)/allure-report/history" "$(System.DefaultWorkingDirectory)/allure-history-output/"

          - task: PublishAllureReport@1
            displayName: "Publish Allure Report"
            inputs:
              testResultsDir: "$(System.DefaultWorkingDirectory)/allure-results"
              allureVersion: "2.34.1"

          - task: PublishPipelineArtifact@1
            displayName: "Publish Allure History"
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/allure-history-output"
              artifact: "allure-history"
              publishLocation: "pipeline"
            condition: succeededOrFailed()
```
