### DISCUSSION TITLE
Use of GitHub Actions with Allure and Playwright

### DISCUSSION THREAD

**Discussion by elAlmani** [allure-framework/allure2#2836] [Bug Reports]
I am using Playwright for e2e-test automation and Allure for test reporting.

This is my yaml file as shown on https://allurereport.org/docs/integrations-github/
(The important stuff is starting below _publish-results_)
```yaml
name: Playwright Tests
on:
  push:
    branches: feature/**
  pull_request:
    branches: [ main, master ]

jobs:
  run-playwright-e2e:
    ...playwright-stuff

  publish-results:
    needs: run-playwright-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: latest-test-results

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          gh_pages: latest-test-results
          allure_history: allure-history
          allure_results: playwright-test-results/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
```

And after every push i am running into a small issue, though i am not sure if it is actually an issue or meant to be that way:
![image](https://github.com/user-attachments/assets/16b38620-051e-4c4e-8b9b-0d44047d9137)

Instead of creating a folder in root repository for every push isn't there a better approach ?
Like for example making it possible to have it inside a defined folder so it doesn't clutter up the root directory. Or only keep a certain amount of tests in the history (e.g. up to 20)

From the current tutorial on https://allurereport.org/docs/integrations-github/ i don't know how to fix this

Any help is appreciated 😄 ❤️ 

Kind Regards
elAlmani
