### DISCUSSION TITLE
Can't see results in the Azure Devops Integration

### DISCUSSION THREAD

**Discussion by KliemannNoah** [allure-framework/allure2#2897] [Questions & Support]
While attempting to integrate the Visual portion of the Allure Azure Devops Integration (https://allurereport.org/docs/integrations-azure/), we have encountered an issue where it seems to be entirely blank.
<img width="1835" alt="TestTrend" src="https://github.com/user-attachments/assets/b3b79dd0-e21f-48fd-ba9d-8a588084f6d5" />
Here you can see that despite recognizing the large number of tests we had previously, it can't register the number of tests in the run, or display any data about them.

I can confirm that we are uploading from the correct location, as our current process has us uploading the raw output as an artifact from the pipeline from that same path right before this step.

Pipeline Artifact Upload:
<img width="427" alt="PipelineArtifact" src="https://github.com/user-attachments/assets/79d03667-18d9-4183-bc8f-7a9d170c21ed" />
 
Allure Integration Upload:
<img width="739" alt="AllureUI" src="https://github.com/user-attachments/assets/b6e7fbe0-7d9c-4e44-8dc8-cc633b0207f8" />

Task yaml:
``` 
  - task: PublishPipelineArtifact@1
    displayName: Publish Allure report xml
    condition: succeededOrFailed()
    inputs:
      targetPath: 'target/site/allure-maven-plugin'
      artifact: 'allure-report-xml-rest-$(databaseType)-$(jobName)-$(Build.BuildNumber)'
      publishLocation: 'pipeline'

  - task: PublishAllureReport@1
    displayName: Publish Allurefor Pipeline UI
    condition: succeededOrFailed()
    inputs:
      testResultsDir: 'target/site/allure-maven-plugin'
```
